apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.1
    helm:
      valueFiles:
      - values.yaml
      values: |
        global:
          openshift: false
        ui:
          enabled: true
          serviceType: "NodePort"
        server:
          dev:
            enabled: true
          ha:
            enabled: true
            raft:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
