# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-test-app
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp-role"
    vault.hashicorp.com/agent-inject-secret-database.txt: "secret/data/myapp/database"
spec:
  # Указываем наш сервисный аккаунт
  serviceAccountName: myapp-sa
  containers:
    - name: app
      image: alpine
      command: ["/bin/sh", "-c", "sleep 5; echo 'Секрет из файла:'; cat /vault/secrets/database.txt; sleep 3600"]
  # restartPolicy: Never
